# Generated by Django 6.0.4 on 2026-04-13 18:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_assets', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.JSONField(default=list, help_text='List of BodyNode paragraph objects')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_block', to='subjects.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ExpandableSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Plain text or simple HTML for section content')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_default_open', models.BooleanField(default=False)),
                ('content_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expandable_sections', to='content.contentblock')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InlineAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='The visible highlighted text', max_length=255)),
                ('annotation_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID embedded in body JSON to link annotated spans to this record', unique=True)),
                ('content_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='content.contentblock')),
                ('media_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='media_assets.mediaasset')),
            ],
        ),
    ]
